version: "3"

services:
        poll:
                build: ./poll
                ports:
                        - "5000:80"
                networks:
                        - poll-tier
                environment: 
                        - 0.0.0.0
                depends_on:
                        - redis
                restart: always
        redis:
                image: redis:alpine
                ports:
                        - "6379"
                networks:
                        - poll-tier
                        - back-tier
                restart: always
        worker:
                build: ./worker
                networks:
                        - back-tier
                environment:
                        - 0.0.0.0
                depends_on:
                        - redis
                        - db
                restart: always
        db:
                image: postgres:latest
                networks:
                        - result-tier
                        - back-tier
                environment:
                        - "POSTGRES_USER=super user"
                        - "POSTGRES_PASSWORD=password"
                volumes:
                        - db-data:/var/lib/mysql/data
                        - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
                restart: always
        result:
                build: ./result
                ports:
                        - "5001:80"
                networks:
                        - result-tier
                environment:
                        - 0.0.0.0
                depends_on:
                        - db
                restart: always
volumes:
        db-data:
networks:
        poll-tier: {}
        result-tier: {}
        back-tier: {}