# This is a basic workflow to help you get started with Actions

name: Auto-Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  pull_request:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make && make re && make clean && make fclean

  Valgrind:
    needs: Build
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2

      - name: Valgrind
        run: make && ./tests/valgrindTest.sh

  Auto-Test-42sh:
    needs: Build
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2

      - name: Command
        run: make && cd tests && ./exit_statusTest.sh
